<a href="https://colab.research.google.com/github/mhsahel/Making_ML_models_and_Evaluation/blob/main/SVM_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
import seaborn as sns

from sklearn.model_selection import train_test_split

In [5]:
# Tips Dataset from seaborn library
df= sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
# Storing Features and Target Cloumn
x = df.iloc[:,1:]
y = df.iloc[:,0]

# Splitting Training And Testing Dataset

In [7]:

X_train , X_test ,y_train , y_test = train_test_split(x,y,test_size = 0.2, random_state = 42 )

In [8]:
X_train

      tip     sex smoker   day    time  size
228  2.72    Male     No   Sat  Dinner     2
208  2.03    Male    Yes   Sat  Dinner     2
96   4.00    Male    Yes   Fri  Dinner     2
167  4.50    Male     No   Sun  Dinner     4
84   2.03    Male     No  Thur   Lunch     2
..    ...     ...    ...   ...     ...   ...
106  4.06    Male    Yes   Sat  Dinner     2
14   3.02  Female     No   Sun  Dinner     2
92   1.00  Female    Yes   Fri  Dinner     2
179  3.55    Male    Yes   Sun  Dinner     2
102  2.50  Female    Yes   Sat  Dinner     3

[195 rows x 6 columns]

# Prepocess The  Features Columns (Sex , Smoker , Time)

In [9]:

from sklearn.preprocessing import LabelEncoder
lr1 = LabelEncoder()
lr2 = LabelEncoder()
lr3 = LabelEncoder()

X_train['sex']= lr1.fit_transform(X_train['sex'])
X_train['smoker']=lr2.fit_transform(X_train['smoker'])
X_train['time']=lr3.fit_transform(X_train['time'])

In [10]:
X_test['sex']= lr1.transform(X_test['sex'])
X_test['smoker']=lr2.transform(X_test['smoker'])
X_test['time']=lr3.transform(X_test['time'])

# One-Hot-Encodeing OF The Feature Column (Day) Using ColumnTransforemer

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [12]:
CT =ColumnTransformer(transformers= (
    [('onehot', OneHotEncoder(drop = 'first'),[3])] ), remainder = 'passthrough')

In [13]:
X_train = CT.fit_transform(X_train)

In [14]:
X_test= CT.transform(X_test)

# SVR Model selection and Train The Model

In [15]:
from sklearn.svm import SVR

In [16]:
svr = SVR(kernel='rbf')
svr.fit(X_train , y_train)

SVR()

# Predict The Model

In [17]:
predict = svr.predict(X_test)

# For The Evaluation Model Using r2_score , mean_absulate_error

In [18]:
from sklearn.metrics import r2_score , mean_absolute_error

In [19]:
print(f'r2_score {r2_score(y_test , predict)}')
print(f'mean_square_error: {mean_absolute_error(y_test , predict)}')

r2_score 0.5502250005312896
mean_square_error: 4.413774883497757

# For Better Accuracy Using GridSearchCV

In [20]:
from sklearn.model_selection import GridSearchCV as gd

In [21]:
params = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}

In [22]:
gdc = gd(estimator=SVR(), param_grid=params , n_jobs=-1)

In [23]:
gdc.fit(X_train ,y_train)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']})

In [24]:
pred = gdc.predict(X_test)

In [25]:
print(f'r2_score at gridsearch_cv : {r2_score(y_test , pred)}')
print(f'mean_square_error at gridsearch_cv : {mean_absolute_error(y_test , pred)}')

r2_score at gridsearch_cv : 0.6200659646053771
mean_square_error at gridsearch_cv : 4.129773285984424

In [27]:
print(f'Best parameters: {gdc.best_params_}')

Best parameters: {'C': 1000, 'gamma': 0.01, 'kernel': 'rbf'}